# Spring Boot configuration
spring:
  application:
    name: employee-service
    #main:
    # allow-bean-definition-overriding: true
    # lazy-initialization: true
  # Database
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://db:3306/employee
      username: root
      password: root
    # JPA properties
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #open-in-view: false
    #generate-ddl: true
  flyway:
    #    locations: filesystem:.\src\main\resources\db\migration
    enabled: true
    #    clean-disabled: true
    baseline-on-migrate: true
#  security:
#    user:
#      name: admin
#      password: admin
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    #org.hibernate: debug
    com.example.demowithtests: debug
# Server configuration
server:
  port: 8086 #set your port
# Swagger configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html # swagger-ui custom path
  api-docs:
    path: /v3/api-docs.yaml
management: # spring actuator
  endpoints:
    #enabled-by-default: true # If changed to false, you can enable separate functionality as indicated below
    #endpoint: # here
    # health:
    #  enabled: true
    web:
      exposure:
        # exclude: "*"
        include: "*"


